name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Simulate Build Step
        run: |
          mkdir -p build-output/dist
          echo "Build Version 1.2.3" > build-output/dist/app.zip
          echo "Build successful."

      - name: Upload Build Artifact (for the reusable workflow to download)
        uses: actions/upload-artifact@v4
        with:
          name: my-project-artifact  # This name must match workflow-artifact-name below
          path: build-output

      # -----------------------------------------------------------
      # CALL THE REUSABLE WORKFLOW TO UPLOAD TO JFROG
      # -----------------------------------------------------------
      - name: Upload to JFrog Artifactory
        uses: ./.github/workflows/upload-artifact.yml # Path to the reusable workflow
        id: jfrog-upload
        with:
          # --- REQUIRED INPUTS ---
          jfrog-url: https://mycompany.jfrog.io           # <-- THIS IS WHERE YOU SUPPLY THE URL
          jfrog-repository: generic-local-repo            # The target repo in Artifactory
          workflow-artifact-name: my-project-artifact     # Name of the artifact uploaded above
          artifact-target-path: latest/production/        # Target path within the repo
          
          # --- OPTIONAL INPUTS (using defaults here) ---
          # archive-artifact: zip # Uncomment if you want to override the default "zip"
          
        secrets:
          jfrog-access-token: ${{ secrets.JFROG_ACCESS_TOKEN }} # Must be configured in your repo secrets
          
      - name: Use Output Path
        run: |
          echo "The artifact was published to: ${{ steps.jfrog-upload.outputs.artifact-path }}"
