name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Simulate Build Step
        run: |
          mkdir -p build-output/dist
          echo "Build Version 1.2.3" > build-output/dist/app.zip
          echo "Build successful."

      - name: Upload Build Artifact (for the reusable workflow to download)
        uses: actions/upload-artifact@v4
        with:
          name: my-project-artifact  # This name must match workflow-artifact-name below
          path: build-output

      # -----------------------------------------------------------
      # CALL THE REUSABLE WORKFLOW TO UPLOAD TO JFROG
      # -----------------------------------------------------------
     # .github/workflows/main-ci.yml (Correct Structure)

      - name: Upload to JFrog Artifactory
        uses: ./.github/workflows/upload-artifact.yml # This line specifies the workflow to call
        id: jfrog-upload
        with: # Inputs passed to the workflow
          jfrog-url: https://mycompany.jfrog.io           
          jfrog-repository: generic-local-repo            
          workflow-artifact-name: my-project-artifact     
          artifact-target-path: latest/production/        
        

          
      - name: Use Output Path
        run: |
          echo "The artifact was published to: ${{ steps.jfrog-upload.outputs.artifact-path }}"
